import { useEffect, useMemo, useState } from 'react';
import { StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { KeyboardAvoidingView } from 'react-native-keyboard-controller';
import { PROPERTY_TYPES, type FloorUse, type PropertyType, type RequirementOccupancy, type RequirementPurpose, type SeekerRequirement } from '@workspace/property-domain';
import { Button } from '@/components/Button';
import { KeyboardAwareScrollViewCompat } from '@/components/KeyboardAwareScrollViewCompat';
import { useColors } from '@/hooks/useColors';
import { useI18n } from '@/contexts/I18nContext';
import { KUWAIT_AREAS, getAreaById, searchAreas } from '@/constants/kuwait-areas';
import { MARKET_CONFIG } from '@/constants/market';
import { generateDomainId } from '@/services/identity';
import { store } from '@/services/persistence';
import { buildPersonRequirement, formValuesFromRequirement, parseOptionalRequirementNumber, preserveHiddenLegacyRentFields } from '@/services/personRequirementWorkflow';

const STEPS = ['purpose', 'type', 'areas', 'budget', 'details', 'notes'] as const;
export default function RequirementEditor() {
  const { requirementId, seekerId } = useLocalSearchParams<{ requirementId: string; seekerId?: string }>();
  const editing = requirementId !== 'new'; const router = useRouter(); const colors = useColors(); const insets = useSafeAreaInsets(); const { t, isRTL, language, fonts } = useI18n();
  const [baseline, setBaseline] = useState<SeekerRequirement | null>(null); const [step, setStep] = useState(0); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const [purpose, setPurpose] = useState<RequirementPurpose>('rent'); const [propertyType, setPropertyType] = useState<PropertyType>('apartment'); const [floorUse, setFloorUse] = useState<FloorUse | undefined>(); const [areas, setAreas] = useState<string[]>([]); const [search, setSearch] = useState('');
  const [minimum, setMinimum] = useState(''); const [maximum, setMaximum] = useState(''); const [currencyCode, setCurrencyCode] = useState<string>(MARKET_CONFIG.currencyCode); const [bedrooms, setBedrooms] = useState(''); const [bathrooms, setBathrooms] = useState(''); const [occupancy, setOccupancy] = useState<RequirementOccupancy | undefined>(); const [services, setServices] = useState<string[]>([]); const [commercialAreaMinimum, setCommercialAreaMinimum] = useState(''); const [commercialAreaMaximum, setCommercialAreaMaximum] = useState(''); const [shopActivity, setShopActivity] = useState(''); const [shopFloor, setShopFloor] = useState(''); const [shopFrontage, setShopFrontage] = useState(''); const [plotAreaMinimum, setPlotAreaMinimum] = useState(''); const [plotAreaMaximum, setPlotAreaMaximum] = useState(''); const [detailFloorCount, setDetailFloorCount] = useState(''); const [apartmentCount, setApartmentCount] = useState(''); const [shopCount, setShopCount] = useState(''); const [intendedUse, setIntendedUse] = useState(''); const [paciNumbersCount, setPaciNumbersCount] = useState(''); const [notes, setNotes] = useState('');
  useEffect(() => { if (!editing) return; void store.getRequirement(requirementId).then(value => { if (!value) { setError(t('requirements.not_found')); return; } setBaseline(value); const form = formValuesFromRequirement(value); setPurpose(form.purpose); setPropertyType(form.propertyType); setFloorUse(form.floorUse); setAreas([...form.preferredAreaIds]); setMinimum(String(form.minimumBudget)); setMaximum(String(form.maximumBudget)); setCurrencyCode(form.currencyCode); setBedrooms(form.bedroomsMinimum === undefined ? '' : String(form.bedroomsMinimum)); setBathrooms(form.bathroomsMinimum === undefined ? '' : String(form.bathroomsMinimum)); setOccupancy(form.occupancy); setServices(['swimmingPool', 'gym', 'seaView', 'centralAC'].filter(key => form[key as keyof typeof form] === true)); setCommercialAreaMinimum(form.minimumBuiltUpAreaSquareMeters === undefined ? '' : String(form.minimumBuiltUpAreaSquareMeters)); setCommercialAreaMaximum(form.maximumBuiltUpAreaSquareMeters === undefined ? '' : String(form.maximumBuiltUpAreaSquareMeters)); setShopActivity(form.commercialActivity ?? ''); setShopFloor(form.floorNumber === undefined ? '' : String(form.floorNumber)); setShopFrontage(form.minimumFrontageWidthMeters === undefined ? '' : String(form.minimumFrontageWidthMeters)); setPlotAreaMinimum(form.minimumPlotAreaSquareMeters === undefined ? '' : String(form.minimumPlotAreaSquareMeters)); setPlotAreaMaximum(form.maximumPlotAreaSquareMeters === undefined ? '' : String(form.maximumPlotAreaSquareMeters)); setDetailFloorCount(form.floorCount === undefined ? '' : String(form.floorCount)); setApartmentCount(form.apartmentCount === undefined ? '' : String(form.apartmentCount)); setShopCount(form.shopCount === undefined ? '' : String(form.shopCount)); setIntendedUse(form.intendedUse ?? ''); setPaciNumbersCount(form.paciNumbersCount === undefined ? '' : String(form.paciNumbersCount)); setNotes(form.notes); }); }, [editing, requirementId, t]);
  const visibleAreas = useMemo(() => search.trim() ? searchAreas(search).filter(area => !areas.includes(area.id)).slice(0, 8) : KUWAIT_AREAS.filter(area => !areas.includes(area.id)).slice(0, 8), [search, areas]);
  const move = (index: number, delta: number) => { const target = index + delta; if (target < 0 || target >= areas.length) return; const next = [...areas]; [next[index], next[target]] = [next[target], next[index]]; setAreas(next); };
  const save = async () => { const ownerId = baseline?.seekerId ?? seekerId; if (!ownerId) { setError(t('requirements.invalid_owner')); return; } if (propertyType === 'floor' && !floorUse) { setError(t('requirements.floor_use_required')); return; }
    const parsed = [parseOptionalRequirementNumber(minimum), parseOptionalRequirementNumber(maximum), parseOptionalRequirementNumber(bedrooms, { integer: true }), parseOptionalRequirementNumber(bathrooms, { integer: true }), parseOptionalRequirementNumber(commercialAreaMinimum), parseOptionalRequirementNumber(commercialAreaMaximum), parseOptionalRequirementNumber(shopFloor, { integer: true }), parseOptionalRequirementNumber(shopFrontage), parseOptionalRequirementNumber(plotAreaMinimum), parseOptionalRequirementNumber(plotAreaMaximum), parseOptionalRequirementNumber(detailFloorCount, { integer: true }), parseOptionalRequirementNumber(apartmentCount, { integer: true }), parseOptionalRequirementNumber(shopCount, { integer: true }), parseOptionalRequirementNumber(paciNumbersCount, { integer: true })];
    if (parsed.some(item => !item.ok)) { setError(t('requirements.invalid_number')); return; }
    const [parsedMinimum, parsedMaximum, parsedBedrooms, parsedBathrooms, parsedCommercialAreaMinimum, parsedCommercialAreaMaximum, parsedShopFloor, parsedShopFrontage, parsedPlotMinimum, parsedPlotMaximum, parsedFloorCount, parsedApartmentCount, parsedShopCount, parsedPaciCount] = parsed as Array<{ ok: true; value: number | undefined }>;
    const commercialFloor = propertyType === 'floor' && floorUse === 'commercial'; const residential = propertyType === 'apartment' || propertyType === 'house' || propertyType === 'villa' || propertyType === 'chalet' || (propertyType === 'floor' && floorUse === 'residential');
    const result = buildPersonRequirement(baseline?.id ?? generateDomainId(), ownerId, { purpose, propertyType, ...(propertyType === 'floor' ? { floorUse } : {}), preferredAreaIds: areas, minimumBudget: parsedMinimum.value, maximumBudget: parsedMaximum.value, currencyCode, notes,
      ...((propertyType === 'shop' || propertyType === 'office' || commercialFloor) ? { minimumBuiltUpAreaSquareMeters: parsedCommercialAreaMinimum.value, maximumBuiltUpAreaSquareMeters: parsedCommercialAreaMaximum.value } : {}),
      ...((propertyType === 'shop' || commercialFloor || propertyType === 'office') ? { ...(shopActivity.trim() ? { commercialActivity: shopActivity.trim() } : {}), ...(parsedShopFloor.value !== undefined ? { floorNumber: parsedShopFloor.value } : {}) } : {}),
      ...((propertyType === 'shop' || commercialFloor) && parsedShopFrontage.value !== undefined ? { minimumFrontageWidthMeters: parsedShopFrontage.value } : {}),
      ...((propertyType === 'commercial_complex' || propertyType === 'whole_building') ? { minimumPlotAreaSquareMeters: parsedPlotMinimum.value, maximumPlotAreaSquareMeters: parsedPlotMaximum.value, floorCount: parsedFloorCount.value, ...(propertyType === 'commercial_complex' ? { shopCount: parsedShopCount.value } : { apartmentCount: parsedApartmentCount.value }) } : {}),
      ...((propertyType === 'office' || commercialFloor) && intendedUse.trim() ? { intendedUse: intendedUse.trim() } : {}),
      ...(commercialFloor && parsedPaciCount.value !== undefined ? { paciNumbersCount: parsedPaciCount.value } : {}),
      ...(purpose === 'rent' && residential ? { bedroomsMinimum: parsedBedrooms.value, bathroomsMinimum: parsedBathrooms.value, ...(occupancy ? { occupancy } : {}), swimmingPool: services.includes('swimmingPool'), gym: services.includes('gym'), seaView: services.includes('seaView'), centralAC: services.includes('centralAC') } : {}) });
    if (!result.ok) { setError(t(`requirements.error.${result.issues[0].code}`)); return; } const replacement = preserveHiddenLegacyRentFields(baseline, result.value); setSaving(true); try { if (baseline) { if (!await store.updateRequirement(baseline, replacement)) throw new Error('REQUIREMENT_CHANGED'); } else await store.saveRequirement(replacement); router.replace(`/person/${encodeURIComponent(ownerId)}` as never); } catch { setError(t('requirements.save_failed')); } finally { setSaving(false); } };
  const choice = (selected: boolean) => [styles.choice, { backgroundColor: selected ? colors.accent : colors.card, borderColor: selected ? colors.turquoise : colors.border }];
  const advance = () => { if (step === 1 && propertyType === 'floor' && !floorUse) { setError(t('requirements.floor_use_required')); return; } setError(''); setStep(value => value + 1); };
  return <View style={[styles.container, { backgroundColor: colors.background, paddingTop: insets.top }]}><View style={[styles.header, { flexDirection: isRTL ? 'row-reverse' : 'row' }]}><TouchableOpacity onPress={() => router.back()}><Text style={{ color: colors.primary }}>{t('capture.cancel')}</Text></TouchableOpacity><Text style={[styles.title, { color: colors.foreground, fontFamily: fonts.bold }]}>{editing ? t('requirements.edit') : t('requirements.add')}</Text><Text style={{ color: colors.mutedForeground }}>{step + 1}/{STEPS.length}</Text></View><KeyboardAvoidingView behavior="padding" style={styles.body}><KeyboardAwareScrollViewCompat contentContainerStyle={styles.content} bottomOffset={80} keyboardShouldPersistTaps="handled">
    {error ? <Text style={{ color: colors.destructive }} testID="requirement-error">{error}</Text> : null}
    {step === 0 && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.purpose')}</Text>{(['rent', 'buy'] as const).map(value => <TouchableOpacity key={value} style={choice(purpose === value)} onPress={() => setPurpose(value)} testID={`requirement-purpose-${value}`}><Text style={{ color: colors.foreground }}>{t(`requirements.purpose.${value}`)}</Text></TouchableOpacity>)}</>}
    {step === 1 && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.property_type')}</Text>{PROPERTY_TYPES.map(value => <TouchableOpacity key={value} style={choice(propertyType === value)} onPress={() => { setPropertyType(value); if (value !== 'floor') setFloorUse(undefined); }} testID={`requirement-type-${value}`}><Text style={{ color: colors.foreground }}>{t(`propertyType.${value}`)}</Text></TouchableOpacity>)}{propertyType === 'floor' ? <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.floor_use')}</Text>{(['residential', 'commercial'] as const).map(value => <TouchableOpacity key={value} style={choice(floorUse === value)} onPress={() => setFloorUse(value)} testID={`requirement-floor-use-${value}`}><Text style={{ color: colors.foreground }}>{t(`requirements.floor_use.${value}`)}</Text></TouchableOpacity>)}</> : null}</>}
    {step === 2 && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.areas')}</Text>{areas.map((id, index) => { const area = getAreaById(id); return <View key={id} style={[styles.area, { borderColor: colors.border }]}><Text style={{ flex: 1, color: colors.foreground }}>{index + 1}. {area ? (language === 'ar' ? area.ar : area.en) : id}</Text><TouchableOpacity onPress={() => move(index, -1)} disabled={index === 0}><Text style={{ color: colors.primary }}>↑</Text></TouchableOpacity><TouchableOpacity onPress={() => move(index, 1)} disabled={index === areas.length - 1}><Text style={{ color: colors.primary }}>↓</Text></TouchableOpacity><TouchableOpacity onPress={() => setAreas(current => current.filter(value => value !== id))}><Text style={{ color: colors.destructive }}>×</Text></TouchableOpacity></View>; })}<TextInput value={search} onChangeText={setSearch} placeholder={t('matching.areas.search')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} />{visibleAreas.map(area => <TouchableOpacity key={area.id} style={choice(false)} onPress={() => { setAreas(current => current.includes(area.id) ? current : [...current, area.id]); setSearch(''); }}><Text style={{ color: colors.foreground }}>+ {language === 'ar' ? area.ar : area.en}</Text></TouchableOpacity>)}</>}
    {step === 3 && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.budget')}</Text><TextInput value={minimum} onChangeText={setMinimum} keyboardType="numeric" placeholder={t('requirements.budget_from')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-budget-min"/><TextInput value={maximum} onChangeText={setMaximum} keyboardType="numeric" placeholder={t('requirements.budget_to')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-budget-max"/><Text style={{ color: colors.mutedForeground }}>{currencyCode}</Text></>}
    {step === 4 && <>{(propertyType === 'shop' || propertyType === 'office' || (propertyType === 'floor' && floorUse === 'commercial')) && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.commercial_area')}</Text><TextInput value={commercialAreaMinimum} onChangeText={setCommercialAreaMinimum} keyboardType="decimal-pad" placeholder={t('requirements.commercial_area_from')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-commercial-area-min"/><TextInput value={commercialAreaMaximum} onChangeText={setCommercialAreaMaximum} keyboardType="decimal-pad" placeholder={t('requirements.commercial_area_to')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-commercial-area-max"/></>}
      {(propertyType === 'shop' || (propertyType === 'floor' && floorUse === 'commercial')) && <><TextInput value={shopActivity} onChangeText={setShopActivity} placeholder={t('requirements.shop_activity')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-shop-activity"/><TextInput value={shopFloor} onChangeText={setShopFloor} keyboardType="number-pad" placeholder={t('requirements.shop_floor')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-shop-floor"/><TextInput value={shopFrontage} onChangeText={setShopFrontage} keyboardType="decimal-pad" placeholder={t('requirements.shop_frontage')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-shop-frontage"/></>}
      {propertyType === 'office' && <><TextInput value={shopFloor} onChangeText={setShopFloor} keyboardType="number-pad" placeholder={t('requirements.shop_floor')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-office-floor"/><TextInput value={intendedUse} onChangeText={setIntendedUse} placeholder={t('requirements.intended_use')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-office-intended-use"/><TextInput value={shopActivity} onChangeText={setShopActivity} placeholder={t('requirements.shop_activity')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-office-activity"/></>}
      {propertyType === 'floor' && floorUse === 'commercial' && <><TextInput value={intendedUse} onChangeText={setIntendedUse} placeholder={t('requirements.intended_use')} style={[styles.input, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-commercial-floor-intended-use"/><TextInput value={paciNumbersCount} onChangeText={setPaciNumbersCount} keyboardType="number-pad" placeholder={t('requirements.paci_numbers_count')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-paci-numbers-count"/></>}
      {(propertyType === 'commercial_complex' || propertyType === 'whole_building') && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.plot_details')}</Text><TextInput value={plotAreaMinimum} onChangeText={setPlotAreaMinimum} keyboardType="decimal-pad" placeholder={t('requirements.plot_area_from')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-plot-area-min"/><TextInput value={plotAreaMaximum} onChangeText={setPlotAreaMaximum} keyboardType="decimal-pad" placeholder={t('requirements.plot_area_to')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-plot-area-max"/><TextInput value={detailFloorCount} onChangeText={setDetailFloorCount} keyboardType="number-pad" placeholder={t('requirements.floor_count')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-floor-count"/><TextInput value={propertyType === 'commercial_complex' ? shopCount : apartmentCount} onChangeText={propertyType === 'commercial_complex' ? setShopCount : setApartmentCount} keyboardType="number-pad" placeholder={t(propertyType === 'commercial_complex' ? 'requirements.shop_count' : 'requirements.apartment_count')} style={[styles.input, { color: colors.foreground, borderColor: colors.border }]} testID="requirement-unit-count"/></>}
      {purpose === 'rent' && (propertyType === 'apartment' || propertyType === 'house' || propertyType === 'villa' || propertyType === 'chalet' || (propertyType === 'floor' && floorUse === 'residential')) && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('matching.rentDetails')}</Text>{([{ label: t('matching.bedrooms'), value: bedrooms, set: setBedrooms, id: 'bedrooms' }, { label: t('matching.bathrooms'), value: bathrooms, set: setBathrooms, id: 'bathrooms' }] as const).map(item => <View key={item.id}><Text style={{ color: colors.foreground }}>{item.label}</Text><View style={[styles.stepper, { flexDirection: isRTL ? 'row-reverse' : 'row', borderColor: colors.border }]}><TouchableOpacity accessibilityRole="button" accessibilityLabel={`${t('requirements.decrease')} ${item.label}`} style={styles.stepperControl} onPress={() => item.set(value => String(Math.max(0, (Number(value) || 0) - 1)))}><Text style={styles.stepperButton}>−</Text></TouchableOpacity><TextInput value={item.value} onChangeText={value => item.set(value.replace(/\D/g, ''))} keyboardType="number-pad" accessibilityLabel={item.label} style={[styles.stepperInput, { color: colors.foreground, textAlign: isRTL ? 'right' : 'left' }]} testID={`requirement-${item.id}`}/><TouchableOpacity accessibilityRole="button" accessibilityLabel={`${t('requirements.increase')} ${item.label}`} style={styles.stepperControl} onPress={() => item.set(value => String((Number(value) || 0) + 1))}><Text style={styles.stepperButton}>+</Text></TouchableOpacity></View></View>)}<Text style={{ color: colors.foreground }}>{t('matching.occupancy')}</Text>{(['family', 'bachelor', 'any'] as const).map(value => <TouchableOpacity key={value} style={choice(occupancy === value)} onPress={() => setOccupancy(current => current === value ? undefined : value)}><Text style={{ color: colors.foreground }}>{t(`matching.occupancy.${value}`)}</Text></TouchableOpacity>)}{(['swimmingPool', 'gym', 'seaView', 'centralAC'] as const).map(value => <TouchableOpacity key={value} style={choice(services.includes(value))} onPress={() => setServices(current => current.includes(value) ? current.filter(item => item !== value) : [...current, value])}><Text style={{ color: colors.foreground }}>{t(`requirements.service.${value}`)}</Text></TouchableOpacity>)}</>}
      {(propertyType === 'warehouse' || propertyType === 'other_built_property') && <Text style={{ color: colors.mutedForeground, textAlign: isRTL ? 'right' : 'left' }} testID="requirement-details-in-notes">{t('requirements.details_in_notes')}</Text>}
      {purpose === 'buy' && propertyType !== 'commercial_complex' && propertyType !== 'whole_building' && propertyType !== 'shop' && propertyType !== 'office' && propertyType !== 'warehouse' && propertyType !== 'other_built_property' && !(propertyType === 'floor' && floorUse === 'commercial') && <Text style={{ color: colors.mutedForeground }}>{t('requirements.buy_no_rent_details')}</Text>}</>}
    {step === 5 && <><Text style={[styles.heading, { color: colors.foreground }]}>{t('requirements.notes')}</Text><TextInput value={notes} onChangeText={setNotes} multiline style={[styles.input, styles.notes, { color: colors.foreground, borderColor: colors.border, textAlign: isRTL ? 'right' : 'left' }]} testID="requirement-notes"/></>}
  </KeyboardAwareScrollViewCompat><View style={[styles.footer, { backgroundColor: colors.background, borderTopColor: colors.border, paddingBottom: Math.max(insets.bottom, 16) }]}><View style={[styles.actions, { flexDirection: isRTL ? 'row-reverse' : 'row' }]}>{step > 0 && <Button title={t('capture.back')} onPress={() => { setError(''); setStep(value => value - 1); }} variant="outline" style={styles.flex}/>}<Button title={step === STEPS.length - 1 ? t('requirements.save') : t('capture.next')} onPress={() => step === STEPS.length - 1 ? void save() : advance()} loading={saving} style={styles.flex} testID={step === STEPS.length - 1 ? 'requirement-save' : 'requirement-next'}/></View></View></KeyboardAvoidingView></View>;
}
const styles = StyleSheet.create({ container: { flex: 1 }, body: { flex: 1 }, header: { alignItems: 'center', justifyContent: 'space-between', padding: 20 }, title: { fontSize: 19 }, content: { padding: 20, gap: 10 }, heading: { fontSize: 21, marginBottom: 8 }, choice: { minHeight: 48, borderWidth: 1, borderRadius: 12, justifyContent: 'center', paddingHorizontal: 14 }, input: { minHeight: 52, borderWidth: 1, borderRadius: 12, paddingHorizontal: 14 }, stepper: { minHeight: 52, borderWidth: 1, borderRadius: 12, alignItems: 'center' }, stepperControl: { minWidth: 44, minHeight: 44, alignItems: 'center', justifyContent: 'center' }, stepperButton: { fontSize: 28 }, stepperInput: { flex: 1, minHeight: 50, fontSize: 17 }, notes: { minHeight: 120, paddingTop: 14, textAlignVertical: 'top' }, area: { minHeight: 48, borderWidth: 1, borderRadius: 12, padding: 12, alignItems: 'center', flexDirection: 'row', gap: 14 }, footer: { borderTopWidth: StyleSheet.hairlineWidth, paddingHorizontal: 20, paddingTop: 12 }, actions: { gap: 10 }, flex: { flex: 1 } });
